const allChefs = [
    {
        role: "CHEF",
        firstName: "Nick",
        lastName: "Arnold",
        bio: "Hailing all the way from Chile, Chef Nick Arnold brings a taste of South American zest to every dish. His culinary creations are like a symphony of flavors, blending spices and ingredients in perfect harmony. When he's not in the kitchen, you might find him salsa dancing with a whisk or perfecting his secret recipe for the world's spiciest salsa. Prepare your taste buds for a fiery and unforgettable culinary adventure!",
        mobileNumber: "555-555-5555",
        email: "nick123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Abby",
        lastName: "Lawson",
        bio: "Chef Abby Lawson is a culinary magician, turning ordinary ingredients into extraordinary gastronomic delights. Her expertise lies in transforming humble dishes into gourmet masterpieces. With a dash of creativity and a sprinkle of magic, she can make even the simplest meal feel like a feast fit for royalty. Be prepared to be spellbound by her culinary spells and experience a symphony of flavors that will leave you craving for more.",
        mobileNumber: "555-555-5555",
        email: "abby123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Gaby",
        lastName: "Sullivan",
        bio: " Chef Gaby Sullivan is a culinary trailblazer with an insatiable passion for pushing boundaries. With her adventurous spirit, she fearlessly experiments with flavors from around the world, fusing unexpected ingredients to create mind-blowing taste sensations. Her dishes are like a rollercoaster ride for your taste buds, taking you on a thrilling journey through uncharted culinary territories. Get ready to embark on a culinary adventure that will challenge your palate and redefine your concept of taste.",
        mobileNumber: "555-555-5555",
        email: "gaby123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Jordan",
        lastName: "Hayes",
        bio: "Chef Jordan Hayes is a culinary virtuoso, transforming the simplest ingredients into extraordinary works of art on a plate. With an impeccable attention to detail and a meticulous approach to cooking, he crafts dishes that are as visually stunning as they are delicious. His creations are like edible symphonies, each bite composing a harmonious melody of flavors. Prepare to be captivated by his culinary compositions and embark on a sensory journey that will delight your senses.",
        mobileNumber: "555-555-5555",
        email: "jordan123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Robert",
        lastName: "Clark",
        bio: "Chef Robert Clarke is a culinary maverick, bringing a rebellious spirit to the world of fine dining. With a mischievous grin and a twinkle in his eye, he defies culinary conventions and creates dishes that break all the rules. His kitchen is his playground, where he transforms traditional recipes into daring and unconventional masterpieces. Brace yourself for a culinary adventure that challenges the status quo and leaves you questioning everything you thought you knew about food.",
        mobileNumber: "555-555-5555",
        email: "robert123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "James",
        lastName: "Montgomery",
        bio: "Chef James Montgomery is a culinary maestro, renowned for his exquisite creations and larger-than-life personality. With a flair for the dramatic, he infuses his dishes with passion and panache, turning every meal into a show-stopping spectacle. From his fiery flambe to his jaw-dropping plating techniques, Chef James is a true entertainer who believes that dining should be an experience to remember. Get ready to be wowed by his culinary theatrics and indulge in a feast fit for royalty.",
        mobileNumber: "555-555-5555",
        email: "james123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Amber",
        lastName: "Lawson",
        bio: "Chef Amber Lawson is a culinary enchantress, weaving magic into every dish she creates. With a sprinkle of pixie dust and a touch of whimsy, she transforms ordinary ingredients into extraordinary culinary delights. Her plates are like a canvas, where she paints vibrant flavors and playful textures. With a mischievous smile and a twinkle in her eye, Chef Amber invites you to step into her world of culinary magic and experience a whimsical journey that will ignite your imagination.",
        mobileNumber: "555-555-5555",
        email: "amber123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Guy",
        lastName: "Thomas",
        bio: "Chef Guy Thompson is a culinary wizard, conjuring up flavors that transport you to distant lands with every bite. With his extraordinary palate and a deep respect for tradition, he masterfully combines classic techniques with modern innovation. His dishes are a testament to his dedication to sourcing the finest ingredients and his unwavering commitment to perfection. Prepare to be spellbound by Chef Guy's culinary sorcery as he takes you on a gastronomic adventure that will tantalize your taste buds. Chef Gaby Sullivan is a culinary trailblazer with an insatiable passion for pushing boundaries. With her adventurous spirit, she fearlessly experiments with flavors from around the world, fusing unexpected ingredients to create mind-blowing taste sensations. Her dishes are like a rollercoaster ride for your taste buds, taking you on a thrilling journey through uncharted culinary territories. Get ready to embark on a culinary adventure that will challenge your palate and redefine your concept of taste.",
        mobileNumber: "555-555-5555",
        email: "guy123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Martha",
        lastName: "Gallagher",
        bio: "Chef Martha Gallagher is a culinary virtuoso, effortlessly creating dishes that capture the essence of comfort and nostalgia. With a warm smile and a motherly touch, she infuses her food with love and passion. Her kitchen is a sanctuary, where she weaves memories and flavors together, creating dishes that soothe the soul. From hearty stews to delicate pastries, Chef Martha's creations are like a warm hug from grandma, reminding you of the simple joys in life.",
        mobileNumber: "555-555-5555",
        email: "martha123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Charles",
        lastName: "Anderson",
        bio: "Chef Charles Anderson is a culinary explorer, constantly seeking inspiration from the farthest corners of the globe. With a thirst for adventure and a voracious appetite for knowledge, he brings a world of flavors to your plate. From the bustling markets of Asia to the vibrant streets of Europe, Chef Charles absorbs the essence of each culture and infuses it into his cooking. Embark on a gastronomic journey with him and let your taste buds travel the world without leaving your seat.",
        mobileNumber: "555-555-5555",
        email: "charles123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Cassandra",
        lastName: "Monroe",
        bio: "Chef Cassandra Monroe is a culinary enchantress, captivating diners with her spellbinding creations. With a touch of elegance and a hint of mystery, she transforms ingredients into culinary masterpieces that are as captivating as they are delicious. Her dishes are a symphony of flavors, each bite unveiling a new layer of complexity. Let Chef Cassandra cast her culinary spell and transport you to a world of gastronomic enchantment where every meal is a magical experience.",
        mobileNumber: "555-555-5555",
        email: "cassandra123@gmail.com",
        password: "123456",
    },
    {
        role: "CHEF",
        firstName: "Tanisha",
        lastName: "Patel",
        bio: "Chef Tanisha Patel is a culinary prodigy, combining her Indian heritage with a modern twist to create flavors that dance on your palate. With a deep reverence for tradition and a fearless spirit of innovation, she blends spices and techniques from her roots with global influences. Her dishes are a celebration of vibrant colors, bold flavors, and a rich tapestry of cultural heritage. Prepare to embark on a gastronomic journey that will take you on an unforgettable tour of India's diverse culinary landscape.",
        mobileNumber: "555-555-5555",
        email: "tanisha123@gmail.com",
        password: "123456",
    },

]

module.exports = {
    allChefs
}